name: 5. Model Deploy

on:
  workflow_dispatch:

jobs:
  deploy-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker run --name lambda-package -d amazonlinux:2 tail -f /dev/null

      - name: Install Python and Dependencies in Docker (Amazon Linux)
        run: |
          docker exec -i lambda-package yum install -y python3-pip zip
          docker exec -i lambda-package pip3 install numpy pandas scipy scikit-learn -t /lambda_package/python

      - name: Add Lambda code and Package everything
        run: |
          docker exec -i lambda-package mkdir -p /lambda_package/lambda
          docker cp src/lambda_model_inference.py lambda-package:/lambda_package/lambda/
          docker exec -i lambda-package bash -c "cd /lambda_package && zip -r /lambda_package.zip ."

      - name: Copy Package to Host
        run: |
          docker cp lambda-package:/lambda_package.zip lambda_model_inference.zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Upload Lambda package to S3
        run: |
          aws s3 cp lambda_model_inference.zip s3://andorra-hotels-data-warehouse/scripts/lambda_model_inference.zip

      - name: Clean up Docker
        run: |
          docker stop lambda-package
          docker rm lambda-package