name: 3. Data Visualization

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create necessary directories
      run: |
        mkdir -p plots
        mkdir -p reports

    - name: Execute Jupyter Notebook
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        jupyter nbconvert --to notebook --execute src/data_visualization.ipynb
    
    - name: Get HTML report
      run: |
        jupyter nbconvert --to html --no-input src/data_visualization.ipynb --output ../reports/data_visualization_l1_$(date +'%Y-%m-%d').html

    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp reports/data_visualization_l1_$(date +'%Y-%m-%d').html s3://andorra-hotels-data-warehouse/l1_data/reports/data_visualization_l1_$(date +'%Y-%m-%d').html

    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages

    - name: Copy HTML report to gh-pages
      run: |
        date=$(date +'%Y-%m-%d')
        cp reports/data_visualization_l1_${date}.html data_visualization_l1_${date}.html
        git config --global user.email "normaescg@gmail.com"
        git config --global user.name "Norma-99"
        git add data_visualization_l1_${date}.html
        git commit -m "Add new data visualization report for ${date}"
        git push origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages