name: 3. Data Visualization

on:
  workflow_dispatch:
    inputs:
      data_level:
        description: 'Choose data visualization level: l1, l2 or nlp'
        required: true
        default: 'l1'
        type: choice
        options:
          - l1
          - l2
          - nlp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create necessary directories
      run: |
        mkdir -p plots
        mkdir -p reports

    - name: Execute Jupyter Notebook
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        jupyter nbconvert --to notebook --execute src/data_visualization_${{ github.event.inputs.data_level }}.ipynb

    - name: Get HTML report
      run: |
        TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
        jupyter nbconvert --to html --no-input src/data_visualization_${{ github.event.inputs.data_level }}.ipynb --output ../reports/data_visualization_${{ github.event.inputs.data_level }}_${TIMESTAMP}.html

    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp reports/data_visualization_${{ github.event.inputs.data_level }}_${TIMESTAMP}.html s3://andorra-hotels-data-warehouse/${{ github.event.inputs.data_level }}_data/reports/data_visualization_${{ github.event.inputs.data_level }}_${TIMESTAMP}.html

    - name: Update index.html
      run: |
        TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
        REPORT_NAME="data_visualization_${{ github.event.inputs.data_level }}_${TIMESTAMP}.html"
        REPORT_LINK="<li><a href='$REPORT_NAME'>${{ github.event.inputs.data_level | upper }} Report (${TIMESTAMP})</a></li>"

        if [ -f reports/index.html ]; then
          sed -i "/<\/ul>/i $REPORT_LINK" reports/index.html
        else
          echo '<!DOCTYPE html>' > reports/index.html
          echo '<html lang="en">' >> reports/index.html
          echo '<head>' >> reports/index.html
          echo '    <meta charset="UTF-8">' >> reports/index.html
          echo '    <meta name="viewport" content="width=device-width, initial-scale=1.0">' >> reports/index.html
          echo '    <title>Data Visualization Reports</title>' >> reports/index.html
          echo '    <link rel="stylesheet" href="styles.css">' >> reports/index.html
          echo '</head>' >> reports/index.html
          echo '<body>' >> reports/index.html
          echo '    <h1>Data Visualization Reports</h1>' >> reports/index.html
          echo '    <ul>' >> reports/index.html
          echo "        $REPORT_LINK" >> reports/index.html
          echo '    </ul>' >> reports/index.html
          echo '</body>' >> reports/index.html
          echo '</html>' >> reports/index.html
        fi

    - name: Create README.md
      run: |
        echo 'To see the pipeline results:' > reports/README.md
        echo '' >> reports/README.md
        echo 'https://norma-99.github.io/HotelRecommendationSystem/' >> reports/README.md

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./reports/
        publish_branch: gh-pages