name: 3. Data Visualization

on:
  workflow_dispatch:
    inputs:
      data_level:
        description: 'Choose data visualization level: l1, l2 or nlp'
        required: true
        default: 'l1'
        type: choice
        options:
          - l1
          - l2
          - nlp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create necessary directories
      run: |
        mkdir -p visualization_site/content/images

    - name: Execute Notebooks
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        jupyter execute src/data_visualization_l1.ipynb src/data_visualization_l2.ipynb src/data_visualization_nlp.ipynb
        cd src
        python retrieve_model_results.py

    - name: Generate HTML
      run: |
        cd visualization_site
        pelican content

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./visualization_site/output
        publish_branch: gh-pages