name: Trigger Lambda Function for Andorran Regions

on:
  workflow_dispatch:

jobs:
  invoke_lambda:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: ['Andorra la Vella', 'Escaldes-Engordany', 'Encamp', 'Canillo', 'La Massana', 'Ordino', 'Sant Julià de Lòria']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Invoke Lambda function for ${{ matrix.region }}
      run: |
        aws lambda invoke \
          --function-name data_gathering_lambda \
          --payload '{"region": "${{ matrix.region }}", "num_hotels": 50, "num_reviews": 100}' \
          response_${{ matrix.region }}.json

    - name: Display Lambda response for ${{ matrix.region }}
      run: |
        cat response_${{ matrix.region }}.json