name: 5. Model Deploy

on:
  workflow_dispatch:

jobs:
  deploy-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker (Amazon Linux)
        run: |
          docker run --name lambda-package -d amazonlinux:2 tail -f /dev/null

      - name: Install Python and Dependencies in Docker (Amazon Linux)
        run: |
          docker exec -i lambda-package yum install -y python3-pip zip
          # Install dependencies in a separate folder
          docker exec -i lambda-package pip3 install --no-deps numpy pandas scipy scikit-learn -t /dependencies
          # Create a zip of just the dependencies
          docker exec -i lambda-package bash -c "cd /dependencies && zip -r /dependencies.zip ."

      - name: Copy dependencies.zip to Host (for upload to S3)
        run: |
          docker cp lambda-package:/dependencies.zip dependencies.zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Upload dependencies.zip to S3
        run: |
          aws s3 cp dependencies.zip s3://andorra-hotels-data-warehouse/scripts/libraries.zip

      - name: Package the Lambda code (without dependencies)
        run: |
          # Ensure lambda_model_inference.py is at the root of the zip
          docker cp src/lambda_model_inference.py lambda-package:/lambda_model_inference.py
          docker exec -i lambda-package zip -r /lambda_package.zip lambda_model_inference.py

      - name: Copy Lambda package to Host
        run: |
          docker cp lambda-package:/lambda_package.zip lambda_model_inference.zip

      - name: Upload Lambda package to S3
        run: |
          aws s3 cp lambda_model_inference.zip s3://andorra-hotels-data-warehouse/scripts/lambda_model_inference.zip

      - name: Clean up Docker
        run: |
          docker stop lambda-package
          docker rm lambda-package