name: 2. Trigger Data Preprocessing

on:
    workflow_dispatch:

jobs:
  trigger-glue-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Trigger AWS Glue Job
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "us-west-2" 
      run: |
        aws glue start-job-run --job-name hotel_data_preprocessing_job