name: 0. Run Pytests

on:
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests with coverage
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-west-2
      run: |
        # Remove any existing coverage data
        coverage erase

        # Run tests with coverage
        coverage run --source=src -m pytest tests/

        # Generate coverage report
        coverage report --show-missing
        coverage xml