name: 3. L1 Data Visualization

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create necessary directories
      run: |
        mkdir -p plots
        mkdir -p reports

    - name: Execute Jupyter Notebook
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        jupyter nbconvert --to notebook --execute src/data_visualization_l1.ipynb

    - name: Get HTML report
      run: |
        jupyter nbconvert --to html --no-input src/data_visualization.ipynb --output ../reports/data_visualization_l1.html

    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp reports/data_visualization_l1.html s3://andorra-hotels-data-warehouse/l1_data/reports/data_visualization_l1_$(date +'%Y-%m-%d').html

    - name: Create index.html
      run: |
        echo '<!DOCTYPE html>' > reports/index.html
        echo '<html lang="en">' >> reports/index.html
        echo '<head>' >> reports/index.html
        echo '    <meta charset="UTF-8">' >> reports/index.html
        echo '    <meta name="viewport" content="width=device-width, initial-scale=1.0">' >> reports/index.html
        echo '    <title>Data Visualization Reports</title>' >> reports/index.html
        echo '</head>' >> reports/index.html
        echo '<body>' >> reports/index.html
        echo '    <h1>Data Visualization Reports</h1>' >> reports/index.html
        echo '    <p>View the latest data visualization report:</p>' >> reports/index.html
        echo '    <a href="data_visualization_l1.html">Latest Report</a>' >> reports/index.html
        echo '</body>' >> reports/index.html
        echo '</html>' >> reports/index.html

    - name: Create README.md
      run: |
        echo 'To see the pipeline results:' > reports/README.md
        echo '' >> reports/README.md
        echo 'https://norma-99.github.io/HotelRecommendationSystem/' >> reports/README.md

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./reports/
        publish_branch: gh-pages